/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidad;

import static contabilidad.frameEditarFrasRec.numProIni;
import static contabilidad.frameFrasRecib.calculaFactura;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteve
 */
public class frameFrasEmitidas extends javax.swing.JFrame {

    /**
     * Creates new form frameFrasEmitidas
     */
    public frameFrasEmitidas() throws SQLException {
        initComponents();
        
        
        //////////////////INICIO INICIALIZACION DEL FRAME/////////////////////////////////
          //PANTALLA COMPLETA 
        this.setExtendedState(MAXIMIZED_BOTH); 
        comboNumCli.setVisible(false);
        radioEditFra.setSelected(false);
        radioEditFra.setEnabled(false);
        radioEditFra.setVisible(false);
        //EJECUTA TODAS LAS TAREAS DE INICIO DE FRAME
        //CAMBIAMOS LOGO
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.jpg")).getImage());
        //DECLARAMOS VARIABLES
        BDControl bd = new BDControl();
        String periodo = bd.leePeriodo();
        String dato[] = new String[7];
        String nombre ="";
        int id=0;
        //TABLA DE FACTURAS RECIBIDAS
        //ESCRIBE TITULO
        String trim =periodo.substring(8);
        String anyo =periodo.substring(0,4);
        etiqTitulo.setText("FACTURAS RECIBIDAS " + trim + "º trimestre del año " + anyo);
      
        //CREAR UN OBJETO MODELO
        DefaultTableModel model = new DefaultTableModel();
       
        //LLENAR CABECERA
        model.addColumn("Número factura");
        model.addColumn("Fecha factura");
        model.addColumn("Cliente");
        model.addColumn("Base");
        model.addColumn("Iva");
        model.addColumn("Total");
        model.addColumn("Vencimiento");
        
         ResultSet datosBD = bd.leeFacturasEmitidas();
         ResultSet idP  ;
         //LLENAR CASILLAS DE TOTALES
         RellenaCasillas rc = new RellenaCasillas();
         String[] respuesta;
         respuesta =  rc.rellenaCamposConta();
         
         textTotBaseTrim.setText(respuesta[0]);
         textTotIvaTrim.setText(respuesta[1]);
         textTotalTrim.setText(respuesta[2]);
         
         //LLENAR TABLA CON DATOS LEIDOS DE LA BASE DE DATOS
         while(datosBD.next()){
             dato[0]=datosBD.getString("numFactura");
             dato[1]=datosBD.getString("fechaFactura");
             id = datosBD.getInt("id_cliente");
             String sql = "SELECT nombre FROM cliente WHERE id_cliente = " + id;
            
             idP = bd.ejecutaSql(sql);
             idP.next();
             try{
                 nombre=idP.getString("nombre");
             }
             catch(Exception e){
                 nombre="**************";
             }
             
             dato[2]=nombre;
             dato[3]=datosBD.getString("base");
             dato[4]=datosBD.getString("iva");
             dato[5]=datosBD.getString("total");
             dato[6]=datosBD.getString("vto");
             model.addRow(dato);
             
         }
       
        tablaFras.setModel(model);
        //FIN LLENAR TABLA
        
          ///////////////////////////////////////////////////////////////////
         
    //LLENAR COMBO CLIENTES
        
        ResultSet clientes = bd.leeClientes();
        String cliente, num_id;
        
        while(clientes.next()){
            cliente = clientes.getString("nombre");
            num_id = clientes.getString("id_cliente");
            comboCli.addItem(cliente);
            comboNumCli.addItem(num_id);
        }
        
  
    //LLENAR DATOS DE TOTALES TRIMESTRE
           
       String datos[]= rc.rellenaCamposConta();
      
       
        
        textTotBaseTrim.setText(datos[0]);
        textTotIvaTrim.setText(datos[1]);
        textTotalTrim.setText(datos[2]);
        
        
    }// FIN FRAMEFRASEMITIDAS
    
    

    
        /////////////////FIN INICIALIZACION DEL FRAME///////////////////////////////
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonInicio = new javax.swing.JButton();
        botonFrasRec = new javax.swing.JButton();
        botonFrasEmi = new javax.swing.JButton();
        botonCuentas = new javax.swing.JButton();
        botonProv = new javax.swing.JButton();
        botonCli = new javax.swing.JButton();
        botonConfig = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textNif = new javax.swing.JTextField();
        comboCli = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNumCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textNumFra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textMO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textMat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textBase = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textTipo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textIva = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        etiqTitulo = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        panelEdicion = new javax.swing.JPanel();
        botonEditar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        textEditFra = new javax.swing.JTextField();
        botonBorrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFras = new javax.swing.JTable();
        botonCerrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        textTotBaseTrim = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textTotIvaTrim = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textTotalTrim = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textVto = new javax.swing.JTextField();
        comboNumCli = new javax.swing.JComboBox<>();
        comboFecha = new org.freixas.jcalendar.JCalendarCombo();
        radioEditFra = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonInicio.setText("Inicio ");
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });

        botonFrasRec.setText("Facturas Recibidas");
        botonFrasRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFrasRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFrasRecActionPerformed(evt);
            }
        });

        botonFrasEmi.setText("Facturas Emitidas");
        botonFrasEmi.setEnabled(false);

        botonCuentas.setText("Cuentas");
        botonCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuentasActionPerformed(evt);
            }
        });

        botonProv.setText("Proveedores");
        botonProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botonCli.setText("Clientes");
        botonCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botonConfig.setText("Configuración");
        botonConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setText("Nombre del Cliente ");

        textNif.setEditable(false);
        textNif.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        comboCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Cliente" }));
        comboCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCliActionPerformed(evt);
            }
        });

        jLabel2.setText("NIF");

        jLabel3.setText("Num. Clente");

        textNumCli.setEditable(false);
        textNumCli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("Num.Factura");

        textNumFra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textNumFra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel7.setText("Mano de Obra");

        textMO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textMO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textMO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textMOFocusLost(evt);
            }
        });

        jLabel8.setText("Material");

        textMat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textMat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textMat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textMatFocusLost(evt);
            }
        });

        jLabel9.setText("Base Imp.");

        textBase.setEditable(false);
        textBase.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textBase.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setText("%");

        textTipo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textTipo.setText("21");
        textTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textTipoFocusLost(evt);
            }
        });

        jLabel11.setText("IVA");

        textIva.setEditable(false);
        textIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textIva.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel12.setText("Total");

        textTotal.setEditable(false);
        textTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        etiqTitulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        etiqTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqTitulo.setText("FACTURAS EMITIDAS");

        botonGuardar.setText("Guardar");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonLimpiar.setText("Limpiar formulario");
        botonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        panelEdicion.setBackground(new java.awt.Color(153, 153, 153));
        panelEdicion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonEditar.setText("Editar Fra.");
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        jLabel13.setText("Numero Factura");

        textEditFra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        botonBorrar.setBackground(new java.awt.Color(153, 102, 255));
        botonBorrar.setText("Borrar Fra.");
        botonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEdicionLayout = new javax.swing.GroupLayout(panelEdicion);
        panelEdicion.setLayout(panelEdicionLayout);
        panelEdicionLayout.setHorizontalGroup(
            panelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(28, 28, 28)
                .addComponent(textEditFra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        panelEdicionLayout.setVerticalGroup(
            panelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEdicionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditar)
                    .addComponent(jLabel13)
                    .addComponent(textEditFra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar))
                .addContainerGap())
        );

        jButton2.setText("Generar Factura en PDF");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaFras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaFras);

        botonCerrar.setText("Cerrar");
        botonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        jLabel14.setText("Total Base Trim.");

        jLabel15.setText("Total IVA Trim.");

        jLabel16.setText("Total Trimestre");

        jLabel17.setText("Fecha Factura");
        jLabel17.setRequestFocusEnabled(false);

        jLabel4.setText("Vencimiento");

        textVto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textVto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textVtoActionPerformed(evt);
            }
        });

        comboNumCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona idCliente" }));

        radioEditFra.setText("Factura Editada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textTotBaseTrim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textTotIvaTrim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textTotalTrim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90)
                                    .addComponent(botonCerrar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFrasRec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFrasEmi)
                                .addGap(18, 18, 18)
                                .addComponent(botonCuentas)
                                .addGap(18, 18, 18)
                                .addComponent(botonProv)
                                .addGap(18, 18, 18)
                                .addComponent(botonCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonConfig)
                                .addGap(155, 155, 155)
                                .addComponent(radioEditFra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboCli, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textNif, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(textNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205)
                                .addComponent(comboNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(textMat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBase, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(textIva, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(254, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(etiqTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43)
                                .addComponent(textVto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textNumFra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonLimpiar)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2)
                                .addGap(154, 154, 154)
                                .addComponent(panelEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonInicio)
                            .addComponent(botonFrasRec)
                            .addComponent(botonFrasEmi)
                            .addComponent(botonCuentas)
                            .addComponent(botonProv)
                            .addComponent(botonCli)
                            .addComponent(botonConfig)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(radioEditFra)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(textNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textNumFra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textVto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(textMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(textBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(textIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(textMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonGuardar)
                        .addComponent(botonLimpiar)
                        .addComponent(jButton2))
                    .addComponent(panelEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(etiqTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCerrar)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(textTotBaseTrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(textTotIvaTrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotalTrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
      this.dispose();
        try { 
            frameContabilidad fc = new frameContabilidad();
            fc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frameFrasRecib.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonFrasRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFrasRecActionPerformed
          this.dispose();
       
      
      
        try {
            
             frameFrasRecib ffr;
             ffr=new frameFrasRecib();
             ffr.setVisible(true);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Ha ocurrido un error", 1);
        }
    }//GEN-LAST:event_botonFrasRecActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void comboCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCliActionPerformed
          BDControl bd = new BDControl();
       ResultSet rs;
       String nif = "*" , ids ="*";
       int id;
        String contenido = comboCli.getSelectedItem().toString();
        try{
            rs = bd.ejecutaSql("SELECT nif,id_cliente FROM cliente WHERE nombre='" + contenido + "'");
            while(rs.next()){
                nif = rs.getString("nif");
                id = rs.getInt("id_cliente");
                ids = Integer.toString(id);
            }
        }
        catch(Exception e){
           nif = "********";
           
        }
       textNif.setText(nif);
       textNumCli.setText(ids);
    }//GEN-LAST:event_comboCliActionPerformed

    private void textMOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMOFocusLost
     
       calculaFactura();
       
    }//GEN-LAST:event_textMOFocusLost

    private void textMatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMatFocusLost
      calculaFactura();
     
    }//GEN-LAST:event_textMatFocusLost

    private void textTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTipoFocusLost
      calculaFactura();
     
    }//GEN-LAST:event_textTipoFocusLost

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
                textBase.setText("");
                textIva.setText("");
                textTotal.setText("");
                textMO.setText("");
                textMat.setText("");
                textTipo.setText("21");
                textNumFra.setText("");
                textNumCli.setText("");
                textNif.setText("");
                textVto.setText("");
                comboCli.setSelectedIndex(0);
                radioEditFra.setSelected(false);
                radioEditFra.setVisible(false);
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
       ///////////////VALIDACION///////////////////////////
         // VALIDACION FECHA
      boolean validado = true;
      int trimIn = 0, trim = 0, anyo = 0;
       BDControl bd = new BDControl();
      //Validar fecha
      
      int anno = comboFecha.getCalendar().get(Calendar.YEAR);
      int mes = comboFecha.getCalendar().get(Calendar.MARCH);
      mes++;
      int dia = comboFecha.getCalendar().get(Calendar.DAY_OF_MONTH);
      
      if(mes<=3 && mes >0){
          trimIn = 1;
      }
      if(mes>3 && mes<=6){
          trimIn = 2;
      }
      if(mes>6 && mes<=9){
          trimIn = 3;
      }
      if(mes>9 && mes<=12){
          trimIn = 4;
      }
                
        try {
            String periodo = bd.leePeriodo();
            
            String t =periodo.substring(8);
            String a =periodo.substring(0,4);
            trim = Integer.parseInt(t);
            anyo = Integer.parseInt(a);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex, "Error al leer periodo",0);
            validado=false;
        }
        if(trimIn != trim || anno != anyo){
            JOptionPane.showMessageDialog(null,"Esta fecha no corresponde al período en el que estamos trabajando", "Atención",0);
            validado=false;
        }
        if(comboCli.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Debes seleccionar un cliente", "Aatención",1);
            validado=false;
        }
        if(textNumFra.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Debes Introducir un  número de factura", "Aatención",1);
            validado=false;
        }
        if(textTotal.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Debes Introducir un  importe", "Aatención",1);
            validado=false;
        }
        //////////FIN DE VALIDACION////////////////////////////////
        //////////SI LA VALIDACION ES CORRECTA GRABAMOS LOS DATOS/////////////////
        if(validado == true){
            if(radioEditFra.isSelected()==true){
                borraFacturaEmit();
            }
            
            int id_cliente = Integer.valueOf(textNumCli.getText()) ;
             String diaS = String.format("%02d",dia) ;
             String mesS = String.format("%02d", mes);
            String fechaFactura = diaS+"/"+mesS+"/"+String.valueOf(anno);
            String fechaOrden = String.valueOf(anno) + mesS + diaS;
            String numFactura = textNumFra.getText();
            String id_cuenta="700000";
            float base = Float.valueOf(textBase.getText()) ;
            float tipo = Float.valueOf(textTipo.getText());
            float iva = Float.valueOf(textIva.getText());
            float total = Float.valueOf(textTotal.getText());
            String vto = textVto.getText();
            float material = 0;
            float mo =0;
            if(textMat.getText().length()!= 0){
                material = Float.valueOf(textMat.getText());
            }
            
            if(textMO.getText().length() != 0){
                 mo = Float.valueOf(textMO.getText());
            }
            
             
          
                    
          try {
              bd.guardaFactEmitidas(id_cliente,fechaFactura,fechaOrden,numFactura,id_cuenta,base,tipo,iva,total,vto,material,mo);
              
          //REESCRIBE LA TABLA DE FACTURAS RECIBIDAS
          this.dispose();
             frameFrasEmitidas ffe = new frameFrasEmitidas();
             
             ffe.setVisible(true);
              
          } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null,ex,"Ha sido imposible guardar la Factura", 1);
          }
            
                    
            
            
           
        }
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textVtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textVtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textVtoActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        //ASIGNAMOS A CADA CAMPO D TEXTO EL VALOR LEIDO DE LA BASE DE DATOS
        if(textEditFra.getText().length() != 0){
            BDControl bd = new BDControl();
            ResultSet rsCli = bd.leeClientes();
            boolean facturaEncontrada = false;
            
           try {
                ResultSet rs = bd.leeFacturasEmitidas();
                
                
                while(rs.next()){
                    if(rs.getString("numFactura").equals(textEditFra.getText())){
                      textNumCli.setText(rs.getString("id_cliente"));
                      textNumFra.setText(rs.getString("numFactura"));
                      
                      textBase.setText(rs.getString("base"));
                      textTipo.setText(rs.getString("tipo"));
                      textIva.setText(rs.getString("iva"));
                      textTotal.setText(rs.getString("total"));
                      textVto.setText(rs.getString("vto"));
                      textMat.setText(rs.getString("material"));
                      textMO.setText(rs.getString("mo"));
                      radioEditFra.setSelected(true);
                      radioEditFra.setVisible(true);
                      
                     
                      //BUSCAMOS N LA TABLA CLIENTES LOS DATOS CORRESPONDIENTES AL ID
                      while(rsCli.next()){
                          if(rsCli.getString("id_cliente").equals(rs.getString("id_cliente"))){
                                String ni = rsCli.getString("nif");
                            textNif.setText(ni);
                            String nombr = rsCli.getString("nombre");
                            comboCli.setSelectedItem(nombr);
                         }
                      }
                      
                      
                     facturaEncontrada=true;
                   
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex, "No se ha podido leer el listado de Facturas emitidas",1);
            
            }if(facturaEncontrada == false){
                JOptionPane.showMessageDialog(null,"La factura num.: "+ textEditFra.getText()+ " no existe.","Resultado de la búsqueda",1);
            }
            
            
            
        } else{ 

            JOptionPane.showMessageDialog(null,"Hay que introducir un número de factura","Atención",1);
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
       borraFacturaEmit();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JOptionPane.showMessageDialog(null,"ESTA FUNCIÓN TODAVÍA NO ESTÁ IMPLEMENTADA", "NOTA INFORMATIVA",1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuentasActionPerformed
        this.dispose();
       
      
      
        try {
            
             frameCuentas fc;
             fc=new frameCuentas();
             fc.setVisible(true);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Ha ocurrido un error", 1);
        }
    }//GEN-LAST:event_botonCuentasActionPerformed
    /////////////////////CALCULA FACTURA///////////////////////////////////////////// 
    public static void calculaFactura(){
      
       String texMo = textMO.getText();
       if(texMo.length()== 0){texMo = "0";}
      String texMate = textMat.getText();
         if(texMate.length()== 0){texMate = "0";}
       String texTip = textTipo.getText();
        if(texTip.length()== 0){texTip = "0";}
       
      
         
            try{

                float mo = Float.valueOf(texMo.trim()).floatValue();
                float i = Float.valueOf(texTip.trim()).floatValue();
                float ma = Float.valueOf(texMate.trim()).floatValue();
                float b = mo + ma;
                float iva = b*i/100;
                float total = b + iva;
                float[] resultados = {iva, total};
                textIva.setText(Float.toString(resultados[0]));
                textTotal.setText(Float.toString(resultados[1]));
                textBase.setText(Float.toString(b));

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Los valores decimales se separan con un punto ","Debes introducir un  valor numérico",2);
                textBase.setText("");
                textIva.setText("");
                textTotal.setText("");
                textMO.setText("");
                textMat.setText("");
       }  
        
        
        
        
      
    }
    ////////////////////////BORRA LA FACTURA QUE HAY EN EL CAMPO EDITAR///////////////////////////////////////
    private static void borraFacturaEmit(){
        
        if(textEditFra.getText().length() != 0){
            BDControl bd = new BDControl();
            boolean fraEncontrada = false;
            
            
            
            
            try {
                ResultSet rs = bd.leeFacturasEmitidas();
                
                while(rs.next()){
                    if(rs.getString("numFactura").equals(textEditFra.getText())){
                   
                     fraEncontrada = true;
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex, "No se ha podido leer el listado de Facturas emitidas",1);
            }
            if(fraEncontrada == true){
                
                int borrado = JOptionPane.showConfirmDialog(null,"Estas a punto de modificar los datos correspondientes a la Factura num.: " +textEditFra.getText() );
           
                if(borrado==0){
                    try{
                                String periodo = bd.leePeriodo();
                        String sql = "DELETE FROM factemi" + periodo + " WHERE numFactura = '" + textEditFra.getText()+"'" ;

                        bd.ejecutaUpdate(sql);
                        
                          //REESCRIBE LA TABLA DE FACTURAS RECIBIDAS
                        if(radioEditFra.isSelected()==false){  
                           frameFrasEmitidas ffe = new frameFrasEmitidas();
                           ffe.dispose();
                           ffe.setVisible(true);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e,"Ha ocurrido un error",1);
                    }        
                }
            }else{
                JOptionPane.showMessageDialog(null,"La factura num.: "+ textEditFra.getText()+ " no existe.","Resultado de la búsqueda",1);
            }
            
            
            
        }else{
            JOptionPane.showMessageDialog(null,"Hay que introducir un número de factura","Atención",1);
        }
    }
    /**
     * @param args the command line arguments
     */
   /* 
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameFrasEmitidas().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonCli;
    private javax.swing.JButton botonConfig;
    private javax.swing.JButton botonCuentas;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonFrasEmi;
    private javax.swing.JButton botonFrasRec;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonProv;
    private javax.swing.JComboBox<String> comboCli;
    private org.freixas.jcalendar.JCalendarCombo comboFecha;
    private javax.swing.JComboBox<String> comboNumCli;
    private javax.swing.JLabel etiqTitulo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelEdicion;
    private static javax.swing.JRadioButton radioEditFra;
    private javax.swing.JTable tablaFras;
    private static javax.swing.JTextField textBase;
    private static javax.swing.JTextField textEditFra;
    private static javax.swing.JTextField textIva;
    private static javax.swing.JTextField textMO;
    private static javax.swing.JTextField textMat;
    private javax.swing.JTextField textNif;
    private javax.swing.JTextField textNumCli;
    private javax.swing.JTextField textNumFra;
    private static javax.swing.JTextField textTipo;
    private javax.swing.JTextField textTotBaseTrim;
    private javax.swing.JTextField textTotIvaTrim;
    private static javax.swing.JTextField textTotal;
    private javax.swing.JTextField textTotalTrim;
    private javax.swing.JTextField textVto;
    // End of variables declaration//GEN-END:variables
}
